# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
commands:
  print_pipeline_id:
    description: "Printing Pipeline Id"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  # print_name:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run: 
  #         name: "echo an ev var that is part of our project"
  #         command: |
  #           echo $USER_NAME
    # save_hello_world_output:
    #   docker:
    #     - image: circleci/node:13.8.0
    #   steps:
    #     - run: echo "text to output here" > ~/output.txt
    #     - persist_to_workspace:
    #         root: ~/
    #         paths:
    #           - output.txt

    # print_output_file:
    #   docker:
    #     - image: circleci/node:13.8.0
    #   steps:
    #     - attach_workspace:
    #         at: ~/
    #     - run: cat ~/output.txt
  new_command_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id



workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - new_command_test
    
