version: 2.1

jobs:
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:99:97:fc:2d:50:92:14:83:f8:d2:b4:41:46:76:f3"
      - run: pip3 install ansible
      - run: ansible-playbook main-remote.yml -i inventory
          

workflows:
  version: 2
  ansible_workflow:
    jobs:
      - config_infrastructure