version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "ab:ad:c5:a1:fe:cd:1a:ce:b9:c3:9c:fe:19:e7:34:6c" # You can gㅇㄹㅇㅎet this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml \
            yes \

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure