version: 2.1

jobs:
  config_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:99:97:fc:2d:50:92:14:83:f8:d2:b4:41:46:76:f3"
      - run:
          name: Execute Ansible Playbook
          command: |
            ansible-playbook main-remote.yml -i inventory

workflows:
  my_workflow:
    jobs:
      - config_infrastructure