- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install node."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install node server"
  become: yes
  copy:
    src: index.js
    dest: index.js
    backup: yes

- name: "Start node server"
  become: yes
  shell:
    cmd: node /home/ubuntu/index.js 